= Deploy Microservices
include::ROOT:page$_attributes.adoc[]

Create an environment variable for your user and log into OpenShift.

Set the workshop user e.g  `export WORKSHOP_USER=<your-username-number>`

[#workshop-set-env]
[source,bash,subs="+macros,+attributes"]
----
#Example:
export WORKSHOP_USER=1 && \
oc login -u user$WORKSHOP_USER  -p  openshift \
   --server {ocpurl}
----
copyToClipboard::workshop-set-env[]

[#deploycustomer]
== Deploy customer

Make sure you are logged in

[#workshop-ocp-login]
[source,bash,subs="+macros,+attributes"]
----
oc whoami
----
copyToClipboard::workshop-ocp-login[]

Go to workshop project 
[#workshop-set-project]
[source,bash,subs="+macros,+attributes"]
----
oc project tutorial{namespace-suffix}
----
copyToClipboard::workshop-set-project[]

Download the tutorial sources

[#workshop-download-sources]
[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/istio-tutorial && cd `basename $_` && \
export TUTORIAL_HOME=`pwd`
----
copyToClipboard::workshop-download-sources[]

Start deploying the microservice projects, starting with customer

ifndef::workshop[]
Make sure `istioctl` is in your `PATH` and it is of version `1.1.7`

[#workshop-check-istioctl]
[source,bash,subs="+macros,+attributes"]
----
$ istioctl version
----
copyToClipboard::workshop-check-istioctl[]
endif::[]

=== Deploy Customer deploy using existing images

:svc-name: customer
:svc-repo: {customer-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

=== Expose customer

Since the `customer` service is the one our users will interact with, let's add an OpenShift Route that exposes that endpoint.

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#deploy-ms-customer]
[source,bash,subs="+macros,+attributes"]
----
kubectl get route -o=jsonpath='{.items[0].spec.host}' &&\
kubectl get pods -w
----
copyToClipboard::deploy-ms-customer[]
--
oc::
+
--
endif::[]
[#deploy-ms-oc-customer]
[source,bash,subs="+macros,+attributes"]
----
oc expose service customer -n tutorial{namespace-suffix} && \
oc get route -n tutorial{namespace-suffix} && \
oc get pods -w -n tutorial{namespace-suffix}
----
copyToClipboard::deploy-ms-oc-customer[]
ifndef::workshop[]
--
====
endif::[]

ifndef::workshop[]
IMPORTANT: If your pod fails with `ImagePullBackOff`, it's possible that your current terminal isn't using the proper Docker Environment. See link:#setup-environment[Setup environment].
endif::[]

Wait until the status is `Running` and there are `2/2` pods in the `Ready` column. To exit, press kbd:[Ctrl+C]

Then test the customer endpoint

:doc-sec: cust
include::ROOT:partial$command-snippets.adoc[tag=call-customer-svc]

You should see the following error because the services `preference` and `recommendation` are not yet deployed.

----
customer => UnknownHostException: preference
----


[#deploypreference]
== Deploy preference

=== Deploy Preference using existing image

:svc-name: preference
:svc-repo: {preference-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

=== Wait preference to be deployed
:doc-sec: pref
include::ROOT:partial$command-snippets.adoc[tag=kgpow]

:doc-sec: pref
include::ROOT:partial$command-snippets.adoc[tag=call-customer-svc]

It will respond with an error since the service `recommendation` is not yet deployed.

NOTE: We could make this a bit more resilient in a future iteration of this tutorial

[source,bash,subs="+macros,+attributes"]
----
customer => Error: 503 - preference => UnknownHostException: recommendation
----

[#deployrecommendation]
== Deploy recommendation

=== Deploy Recommendation using existing images

:svc-name: recommendation
:svc-repo: {recommendation-repo}
include::ROOT:partial$deploy-microservice.adoc[tag=deploy]

=== Wait recommendation to be deployed

:doc-sec: recommendation
include::ROOT:partial$command-snippets.adoc[tag=kgpow]

:doc-sec: recommendation
include::ROOT:partial$command-snippets.adoc[tag=call-customer-svc]
it should now return

[source,bash,subs="+macros,+attributes"]
----
customer => preference => recommendation v1 from '99634814-sf4cl': 1
----

